Create TABLE GameDetails (
	    GAME_ID int not null ,
        TEAM_ID int  references public."Teams"("TEAM_ID") not null,
	    TEAM_ABBREVIATION varchar(3),
	TEAM_CITY text,
        PLAYER_ID int  references public."Players"("PLAYER_ID") not null,
	    PLAYER_NAME varchar(100) not null,
	   MINIMUM varchar,
	FGM double precision ,
	FGA double precision,
	FG_PCT double precision,
	FG3M double precision,
	FG3A double precision,
	FG3_PCT double precision,
	FTM double precision,
	FTA double precision,
	FT_PCT double precision,
	OREB double precision,
	DREB double precision,
	REB double precision,
	AST double precision,
	STL double precision,
	BLK double precision,
	FOUL double precision,
	PF double precision,
	PTS  double precision,
	PLUS_MINUS  double precision,
    PRIMARY KEY(GAME_ID,TEAM_ID,PLAYER_ID)
);